apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SalifAbdoulSow18/immo-app.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: immo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true